### ISSUE TITLE
"Fatal error: spawn ok" while running grunt build on Windows 7

### ISSUE THREAD

**Issue by dchaboya** [Esri/dojo-bootstrap-map-js#49]
I aware of the other issue that was posted by [Rahul](https://github.com/Esri/dojo-bootstrap-map-js/issues/48) on this topic.  However, using PowerShell did not fix the problem.  I tried running the command in cygwin, git bash, and cmd and received the same error.

**Comment by davewilton** [comment]
@tomwayson FYI in case anyone gets this issue I got this issue on a windows vm because java path was not set. Get them to test java -version. This made me realise grunt-dojo uses java rather than running with node.js which is about twice as slow to run...
