### ISSUE TITLE
"LayerClass is not a constructor" when not using webmap

### ISSUE THREAD

**Issue by npeihl** [Esri/dojo-bootstrap-map-js#71]
Hi Tom,
I just pulled down the latest commits and the sidebar looks great. Unfortunately, when I change the config to not use a webmap, I receive a "LayerClass is not a constructor" error. I believe [this line](https://github.com/Esri/dojo-bootstrap-map-js/blame/master/src/app/mapping/MapControls.js#L98) is not passing the LayerClass correctly to initLayer.

**Comment by tomwayson** [comment]
Thanks @npeihl - as you can tell I only tested w/ web maps. I'll take a look at this as soon as I can.
